import { describe, it, expect } from "vitest";
import { parseWorkbook } from "./parseWorkbook";
import { DATASET_SCHEMAS } from "../datasets";

// This tsconfig targets the browser (no @types/node), but the test runner bundles to
// CJS on platform:node, so `require` and node built-ins exist at runtime. Declare them
// locally so we can read the committed pack files without pulling node types into the
// app's typecheck.
declare const require: (m: string) => any;
declare const process: { cwd(): string };
const fs = require("node:fs");
const path = require("node:path");

// Guards the shipped sample intake pack (sample-data/intake-pack/*.xlsx, generated by
// `npm run intake-pack`): every workbook must still ingest cleanly through the real
// importer. The pack is what we hand to prospects for live-upload demos, so a schema
// or alias change that quietly breaks ingestion would be embarrassing in front of a
// customer — this catches it in CI. Reads the committed .xlsx files and parses each
// against its dataset kind, asserting all canonical columns map and rows import.
const DIR = path.resolve(process.cwd(), "sample-data/intake-pack");

// filename → dataset kind (mirrors scripts/gen-intake-pack.mjs output).
const FILES: ReadonlyArray<readonly [string, string]> = [
  ["01_Employee_Master_2026-04-05.xlsx", "employee_master"],
  ["02_Employee_Master_2026-05-05.xlsx", "employee_master"],
  ["03_Talent_Acquisition_Requisitions_2026-05.xlsx", "ta_requisition"],
  ["04_Performance_Review_Cycle_FY26-H1.xlsx", "pms_review"],
  ["05_Payroll_Per_Employee_Detail_2026-05.xlsx", "payroll_record"],
  ["06_Payroll_Department_Aggregate_2026-05.xlsx", "payroll_aggregate"],
  ["07_Payroll_Statutory_Compliance_2026-05.xlsx", "payroll_statutory"],
  ["08_L_D_Programs_2026-05.xlsx", "ld_program"],
  ["09_L_D_Enrollments_2026-05.xlsx", "ld_enrollment"],
  ["10_HR_Admin_Assets_2026-05.xlsx", "admin_asset"],
  ["11_HR_Admin_Contracts_AMC_2026-05.xlsx", "admin_contract"],
  ["12_HR_Admin_Onboarding_Offboarding_2026-05.xlsx", "admin_lifecycle"],
  ["13_Engagement_Survey_2026-05.xlsx", "engagement_survey"],
  ["14_Planning_Headcount_Plan_2026-05.xlsx", "headcount_plan"],
];

describe("sample intake pack ingests cleanly", () => {
  it("ships all 14 workbooks", () => {
    expect(fs.existsSync(DIR)).toBe(true);
    for (const [file] of FILES) expect(fs.existsSync(path.join(DIR, file))).toBe(true);
  });

  for (const [file, kind] of FILES) {
    it(`${file} imports as ${kind} with every column mapped`, async () => {
      const buf = fs.readFileSync(path.join(DIR, file));
      const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
      const cand = await parseWorkbook(ab, file, DATASET_SCHEMAS[kind]);
      expect(cand.status).toBe("imported");
      expect(cand.kind).toBe(kind);
      expect(cand.rowCount).toBeGreaterThan(0);
      expect(cand.rows.length).toBe(cand.rowCount);
      // Headers are the schema's own labels, so nothing should be left unmapped.
      expect(cand.missingColumns.length).toBe(0);
      expect(cand.compatibility === "full" || cand.compatibility === "compatible_with_warnings").toBe(true);
    });
  }
});
