import * as XLSX from "xlsx";
import { DatasetSchema } from "../datasets";
import { coerce } from "./coerce";
import { parsePeriod, resolveMonthDayYear } from "./period";
import { validateRows, checkReferentialIntegrity } from "./validate";
import type { Row, SnapshotCandidate } from "./types";

const pad2 = (n: number) => String(n).padStart(2, "0");

// HRMS exports (Keka and others) wrap the data in a company banner above the
// header and a "Generated on <date> … generated by <vendor>" trailer below it.
// The banner sits above the detected header row so it's skipped naturally; the
// trailer lands in the data range, so recognise it to (a) never import it as an
// employee and (b) harvest its date as a fallback as-of when the filename has none.
const TRAILER_RE = /generated\s+(on|by)\b|this report is generated|\bkeka\b/i;
const isTrailerRow = (values: unknown[]): boolean => values.some((v) => TRAILER_RE.test(String(v ?? "")));
function trailerDate(values: unknown[]): string | null {
  for (const v of values) {
    const m = String(v ?? "").match(/generated on\s+(.+?)(?:\s+by\b|$)/i);
    if (m) {
      const d = new Date(m[1].trim());
      if (!Number.isNaN(d.getTime())) return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
    }
  }
  return null;
}

export async function parseWorkbook(
  data: ArrayBuffer,
  fileName: string,
  schema: DatasetSchema,
  overrideAsOf?: string,
  knownEmployeeIds?: Set<string> | null,
  fallbackToday?: string,
): Promise<SnapshotCandidate> {
  const wb = XLSX.read(data, { type: "array", cellDates: true });
  const alias = schema.aliasMap();
  const canonical = new Set(schema.columnNames);
  const dtypeByField = new Map(schema.fields.map((fld) => [fld.name, fld.dtype] as const));

  let best: { sheet: string; headerRow: number; headers: string[]; score: number } | null = null;
  for (const sheetName of wb.SheetNames) {
    const aoa = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName], { header: 1, blankrows: false });
    const scan = Math.min(10, aoa.length);
    for (let r = 0; r < scan; r++) {
      const headers = (aoa[r] || []).map((v) => (v == null ? "" : String(v).trim()));
      const mapped = headers
        .map((h) => alias[h.toLowerCase()])
        .filter((c): c is string => !!c && canonical.has(c));
      const score = new Set(mapped).size;
      if (!best || score > best.score) best = { sheet: sheetName, headerRow: r, headers, score };
    }
  }

  const period = parsePeriod(fileName, schema.periodKind);
  // Override > filename date > (year-less filename month/day resolved against today).
  let asOf = overrideAsOf ?? period.asOf;
  if (!asOf && period.monthDay && fallbackToday) asOf = resolveMonthDayYear(period.monthDay.month, period.monthDay.day, fallbackToday) ?? null;
  const threshold = Math.max(1, Math.min(2, schema.keyFields.length));
  if (!best || best.score < threshold) {
    return reject(schema, fileName, asOf, period.periodLabel, "No sheet matched the template columns.");
  }

  const headerToField = best.headers.map((h) => alias[h.toLowerCase()]);
  const available = new Set(headerToField.filter((c): c is string => !!c && canonical.has(c)));
  const aoa = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[best.sheet], { header: 1, blankrows: false });
  const rows: Row[] = [];
  const rawRows: Record<string, unknown>[] = []; // pre-coercion values, for validation
  let trailerAsOf: string | null = null;
  for (let r = best.headerRow + 1; r < aoa.length; r++) {
    const values = (aoa[r] || []) as unknown[];
    if (isTrailerRow(values)) { trailerAsOf = trailerAsOf ?? trailerDate(values); continue; }
    const row: Row = Object.fromEntries(schema.columnNames.map((n) => [n, null]));
    const raw: Record<string, unknown> = {};
    let hasData = false;
    best.headers.forEach((_, ci) => {
      const field = headerToField[ci];
      if (!field || !canonical.has(field)) return;
      raw[field] = values[ci];
      const c = coerce(dtypeByField.get(field)!, values[ci]);
      row[field] = c;
      if (c !== null && c !== "") hasData = true;
    });
    if (!hasData) continue;
    if (schema.keyFields.length && !schema.keyFields.some((k) => row[k] !== null && row[k] !== "")) continue;
    // Fill defaults for fields whose column is absent from the file (e.g. a
    // roster export with no employment_status column → default to "Working").
    for (const [fld, val] of Object.entries(schema.defaults)) {
      if (!available.has(fld) && (row[fld] === null || row[fld] === "")) row[fld] = coerce(dtypeByField.get(fld) ?? "string", val);
    }
    rows.push(row);
    rawRows.push(raw);
  }
  const { issues: valIssues } = validateRows(schema, rawRows, available);
  const refIssues = checkReferentialIntegrity(schema, rawRows, knownEmployeeIds);
  const issues = [...valIssues, ...refIssues].sort((a, b) => a.row - b.row);
  const rowsWithIssues = new Set(issues.map((i) => i.row)).size;

  // Fields filled from schema defaults count as available (so they show in the
  // preview and don't read as "missing"). Validation above ran on real columns only.
  for (const fld of Object.keys(schema.defaults)) if (canonical.has(fld) && !available.has(fld)) available.add(fld);

  // Prefer an explicit override or a filename date; otherwise fall back to a date
  // harvested from an export trailer ("Generated on …").
  const effectiveAsOf = asOf ?? trailerAsOf;
  const inferredFromMonthDay = !overrideAsOf && !period.asOf && !!period.monthDay && !!asOf;
  const trailerNote = !asOf && trailerAsOf ? `As-of ${trailerAsOf} read from the export's “Generated on” footer.` : null;
  const asOfNote = inferredFromMonthDay ? `As-of ${asOf} inferred from the filename (no year given) — change it above if that's wrong.` : trailerNote;
  const missing = schema.columnNames.filter((c) => !available.has(c));
  const compatibility = determineCompatibility(available, schema);
  const status: SnapshotCandidate["status"] = compatibility !== "rejected" && effectiveAsOf ? "imported" : "rejected";
  return {
    kind: schema.kind,
    sourceFile: fileName,
    asOf: effectiveAsOf,
    periodLabel: overrideAsOf ?? period.periodLabel ?? asOf ?? trailerAsOf,
    detectedSheet: best.sheet,
    availableColumns: [...available].sort(),
    missingColumns: missing,
    compatibility,
    rowCount: rows.length,
    status,
    rows,
    notes: status === "imported" ? [asOfNote ?? period.note] : [period.note, "Rejected — missing required columns or period."],
    issues,
    rowsWithIssues,
  };
}

function determineCompatibility(
  available: Set<string>,
  schema: DatasetSchema,
): SnapshotCandidate["compatibility"] {
  const required = schema.requiredFields();
  const all = new Set(schema.columnNames);
  const hasAllRequired = [...required].every((c) => available.has(c));
  if (hasAllRequired) return [...all].every((c) => available.has(c)) ? "full" : "compatible_with_warnings";
  if (schema.keyFields.every((c) => available.has(c))) return "partial";
  return "rejected";
}

function reject(
  schema: DatasetSchema,
  fileName: string,
  asOf: string | null,
  label: string | null,
  msg: string,
): SnapshotCandidate {
  return {
    kind: schema.kind,
    sourceFile: fileName,
    asOf,
    periodLabel: label,
    detectedSheet: null,
    availableColumns: [],
    missingColumns: [...schema.columnNames],
    compatibility: "rejected",
    rowCount: 0,
    status: "rejected",
    rows: [],
    notes: [msg],
    issues: [],
    rowsWithIssues: 0,
  };
}
