// Embed the sample workspace as the shipped demo dataset.
//
// Reads the committed gzipped sample workspace and writes it, base64-encoded,
// into src/demo/demoWorkspace.ts so the single-file build can ship a fully
// populated demo with no network fetch. The bytes are the exact same gzipped
// workspace format that loadWorkspace() consumes, so demo mode is just a normal
// workspace load from in-memory bytes.
//
// Regenerate whenever the sample changes:  npm run embed-demo
//   (the sample itself is produced by  npm run sample-data)

import * as fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(root, "sample-data", "Airpay-HR-sample-workspace.json.gz");
const OUT = path.join(root, "src", "demo", "demoWorkspace.ts");

const bytes = fs.readFileSync(SRC);
const b64 = bytes.toString("base64");

const banner = `// AUTO-GENERATED by scripts/embed-demo.mjs — do not edit by hand.
// Base64 of sample-data/Airpay-HR-sample-workspace.json.gz (${bytes.length.toLocaleString("en-US")} bytes
// gzipped). This is the workspace the tool ships in "demo mode" so a first-time
// user sees a fully populated product before uploading any data. Regenerate
// with: npm run embed-demo
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, `${banner}export const DEMO_WORKSPACE_B64 =\n  "${b64}";\n`);

console.log(`embedded demo workspace → src/demo/demoWorkspace.ts (${bytes.length} bytes → ${b64.length} b64 chars)`);
